
@baseUrl = http://localhost:3000

#Messages
### Lista todos os recados
GET {{baseUrl}}/messages/?limit={{$randomInt 1 100}}&offset={{$randomInt 0 100}}
### Lista apenas um recado
GET {{baseUrl}}/messages/2
### Cria um recado
POST {{baseUrl}}/messages
Content-Type: application/json

  {
    "text": "New message 643234",
    "to": "dasdsadsadsa",
    "from": "Gabriel"
  }

### Atualiza um recado
PATCH {{baseUrl}}/messages/4
Content-Type: application/json

  {
    "isRead": false
  }

### Apaga um recado
DELETE {{baseUrl}}/messages/3

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

# @name ExemploDeRota
GET {{baseUrl}}/home/example