
@baseUrl = http://localhost:3000

#Messages
### Lista todos os recados
GET {{baseUrl}}/messages/?limit=10&offset=0
Authorization: Bearer tokenMock
### Lista apenas um recado
GET {{baseUrl}}/messages/1
### Cria um recado
POST {{baseUrl}}/messages
Content-Type: application/json

  {
    "text": "De gabriel 1 para gabriel 2 e 3",
    "receiversId": [2, 3],
    "senderId": 1
  }

### Atualiza um recado
PATCH {{baseUrl}}/messages/1
Content-Type: application/json

  {
    "text": "Editei a msgds"
  }

### Apaga um recado
DELETE {{baseUrl}}/messages/8



#Messages
### Lista todos os Usuários
GET {{baseUrl}}/users/?limit={{$randomInt 1 100}}&offset={{$randomInt 0 100}}
### Lista apenas um Usuário
GET {{baseUrl}}/users/2
### Cria um Usuário
POST {{baseUrl}}/users
Content-Type: application/json

  {
    "name": "Gabriel 3",
    "email": "a@b.com",
    "passwordHash": "654321"
  }

### Atualiza um recado
PATCH {{baseUrl}}/users/14
Content-Type: application/json

  {
    "email": "a@bsdaadsds.com",
    "passwordHash": "123456"
   }

### Apaga um recado
DELETE {{baseUrl}}/users/15