
@baseUrl = http://localhost:3000

#Messages
### Lista todos os recados
GET {{baseUrl}}/messages/?limit={{$randomInt 1 100}}&offset={{$randomInt 0 100}}
### Lista apenas um recado
GET {{baseUrl}}/messages/5
### Cria um recado
POST {{baseUrl}}/messages
Content-Type: application/json

  {
    "text": "New message 3",
    "to": "dasdsadsadsa",
    "from": "Gabriel"
  }

### Atualiza um recado
PATCH {{baseUrl}}/messages/1
Content-Type: application/json

  {
    "text": "Id 4 updated",
    "to": "zap",
    "from": "Gabriel",
    "isRead": false,
    "date": "2025-06-20T20:52:00.848Z"
  }

### Apaga um recado
DELETE {{baseUrl}}/messages/1

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

# @name ExemploDeRota
GET {{baseUrl}}/home/example